Program Design - lab8

Student Name   : Wade-Lin
School Noumber : F44026123 
Github Account : WadeLin3
Update Date    : 2017/6/19

Prob.1 Explain why the program terminates without showing “I love C++.”

After executing the program, the error message appear as

	>terminate called without an active exception
	>Aborted

This result is due to the exception error. Because there is a "throw" action in the line 5 and no one can catch this exception, the program called the termination automatically and implicity. Hence, the program shut down and print hte "Aborted" message.

Prob.2 Does the program show “I love C++”? Why?

The answer is No. Same as Prob.1, I exceute the program and get the following error message

	>terminate called after throwing an instance of 'double'
	>Aborted

The error message tell us that the program terminate after a "throw" action which it throw a "double" type object out. Then again, no one catch this exception and cause the program shut down.
If we change the object type "float" in the catch function in line 7 to "double", then, we gain the correct excecution. (See lab8_2-modified.cpp)

	>exception caught
	>I love C++

The exception catched sucessfully by the double type of catch function.

Prob.3

Add a set_new_handler in genMino.cpp.
